[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.62.0",
    "plotly>=6.0.0",
    "pypdf2>=3.0.1",
    "python-docx>=1.1.2",
    "streamlit>=1.42.0",
]
