[server]
headless = true
enableCORS = true
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#007bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"

[browser]
gatherUsageStats = false

[logger]
level = "info"