[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#007bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"

[browser]
gatherUsageStats = false

[logger]
level = "info"